### PR TITLE
Update for lwt 4.0.0

### PR DESCRIPTION
**Pull request by ncihnegn**
Using core_kernel.Doubly_linked and lwt_log.

### CODE REVIEW

**Comment by rgrinberg** [comment]
I don't think introducing core_kernel is possible (or even desirable). The breaking change should be towards making the hooks abstract IMO. The other changes are fine.

**Comment by ncihnegn** [comment]
Is it license issue? Could you please elaborate?

**Comment by rgrinberg** [comment]
It's a huge dependency that's being acquired for a data structure that's quite easy to implement. In particular, I'm not sure how portable core_kernel is on windows.

Why not just inline some simple implementation into the source and keep it abstract? To prevent issues such as this happening in the future.

**Comment by rgrinberg** [comment]
Thanks, that's a step in the right direction. A few points:

* Could you split out the Camomile change into its own commit? This is unrelated to updating things to Lwt.

* Could you explain the changes to src/lTerm_windows_stubs.c. Ideally, those should be in their own commit as well. With the message describing the change.

* We shouldn't be squatting the name `Lwt_dlist`. That name really belongs to the Lwt package, so something like `lTerm_dlist.ml` is a lot better.

* Do we really need a dlist?

We can see that the callbacks module only after adds on the left of this list. If we're going to make a breaking change, why not make something more future proof:

```ocaml
type switch

type 'a callbacks

val create : unit -> 'a callbacks

val fold_left : ('acc -> 'a -> 'acc) -> 'a callbacks -> 'acc -> 'acc

val register : switch option -> 'a callbacks -> 'a -> unit

val exec_callbacks : ('a -> unit) callbacks -> 'a -> unit

val exec_filters : ('a -> bool) callbacks -> 'a -> bool
```

It doesn't seem like the `add_r` is even being used anywhere by the users of lambda-term, so I wonder if we can even implement `type 'a callbacks = 'a list ref` (but keep things abstract of course).

**Comment by rgrinberg** [comment]
Okay, I see. So we'll have to keep the dlist under the hood.

**Comment by ncihnegn** [comment]
To fix #60

**Comment by diml** [comment]
This PR looks ready. I'm merging it and doing a release since it's blocking `opam upgrade`.

**Comment by diml** [comment]
And thanks for this PR!

**Pull request merged**
